### ISSUE TITLE
Customize global variable and allow path based mapping

### ISSUE THREAD

**Issue by marcospassos** [mairatma/babel-globals#1]
Hey Maira, thanks for sharing this aewsome library with us, great job! It's a powerful tool for creating bundled libraries that does not need heavy module loaders.

I've a few use cases not covered by the documentation. Could you please help me?

1 - Using the following setup, the resulting file is uncompiled for some unknown reason:
I'm using  `"babel-plugin-globals": "^1.0.1"`, `"gulp": "^3.9.0"` and `"gulp-babel": "^5.2.1"`.

Source:

``` js
class Foo {
  bar() {
    return 'baz';
  }
}

export default Foo;
```

Setup:

``` js
  gulp.task('build', function() {
    return gulp.src(['Foo.js'])
      .pipe(babelGlobal({globalName: 'foo'}))
      .pipe(gulp.dest('./dist/'));
});
```

Result:

``` js
this.foo = this.foo || {};
this.fooNamed = this.fooNamed || {};
(function (global) {
  var babelHelpers = global.babelHelpers = {};
})(typeof global === "undefined" ? self : global);
(function () {
  class Foo {
    bar() {
      return 'baz';
    }
  }
}).call(this);
```

If I run the compiler after the plugin, the variable `this` becomes `undefined` and a prefix "babel" is added to the variable key:

``` js
  gulp.task('build', function() {
    return gulp.src(['Foo.js'])
      .pipe(babelGlobal({globalName: 'foo'}))
      .pipe(plugins.babel({modules: 'ignore', comments: false, optional: ['runtime']}))
      .pipe(gulp.dest('./dist/'));
});
```

Result:

``` js
"use strict";

undefined.foo = undefined.foo || {};
undefined.fooNamed = undefined.fooNamed || {};
(function (global) {
  var babelHelpers = global.babelHelpers = {};
})(typeof global === "undefined" ? self : global);
(function () {
  var Foo = (function () {
    function Foo() {
      _classCallCheck(this, Foo);
    }

    _createClass(Foo, [{
      key: "bar",
      value: function bar() {
        return 'baz';
      }
    }]);

   this.foo.babel= Foo;
  })();
}).call(undefined);
```

2 - How can I disable the declaration of the variable `fooNamed`?
3 - I would like to customize the variable name, in order to use `window` instead of `this`. Is it possible?
4 - How can I include the path of the file in the variable key? Currently, two classes sharing the same name will override each other. Something like an option to specify whether the path should be considered would be really useful.

Example:

Given the class `Foo` is under `foo/bar`:

``` js
class Foo {
  bar() {
    return 'baz';
  }
}
export default Foo;
```

And `Bar` is under `/`:

``` js
import Foo from 'foo/bar'
class Bar {
}
export default Bar;
```

I expect the output:

``` js
this.foo = this.foo || {};
this.fooNamed = this.fooNamed || {};
(function (global) {
  var babelHelpers = global.babelHelpers = {};
})(typeof global === "undefined" ? self : global);
(function () {
  //...
 this.foo['foo/bar/Foo'] = Foo;
  //...
}).call(this);
(function () {
  var Foo = this.foo['foo/bar/Foo'];
  //...
}).call(this);
```

Thanks in advance!

**Comment by mairatma** [comment]
Hi @marcospassos! I'm very glad that this has turned out useful for other people as well :)

Let me address your questions one by one:
1) This is my fault, it's happening because I've recently updated babel-globals to use [Babel 6](http://babeljs.io/blog/2015/10/29/6.0.0/), but I've forgotten to update the documentation. Babel 6 doesn't transpile classes or any other ES2015 syntax automatically anymore, you have to manually add the plugins/presets you want to use now. You can see an example of how to do this on the [test](https://github.com/mairatma/babel-globals/blob/master/test/test.js#L24) I've created for using classes. You probably want to use all of ES2015 though, so I'd recommend using the **es2015** preset instead. Take a look at the [Babel 6 release documentation](http://babeljs.io/blog/2015/10/29/6.0.0/) to learn how to do it. I'll update the documentation for **babel-globals** to reflect this now, thanks a lot for pointing it out!

2) There's no way to disable it right now, but I could add an option for that.

3) Using `this` should already be enough in most cases, since it resolves to `window` in browsers, unless the file is included inside some other context instead of on its own. Giving the option to change this could be useful though, it could even allow exporting to a non global variable, so I'll add it to the todo list as well.

4) I like the path idea too, there could be different modes of exporting to globals, the current one and this.

Thanks a lot for this feedback! I'll create separate issues for these 4 suggestions, just to keep things organized. I'll try to work on some of them soon, but feel free to send a pr to any of them if you wish as well.

**Comment by marcospassos** [comment]
Hey @mairatma, thanks for your accurate answer.

The path idea is one of the most useful for us, once it generates a namespace aware structure which allows using any class of the package from external modules. Another approach for achieving it involves building an object tree instead of a map:

``` js
this.Acme = this.Acme || {};
this.AcmeNamed = this.AcmeNamed || {};

(function (global) {
  var babelHelpers = global.babelHelpers = {};
})(typeof global === "undefined" ? self : global);

(function () {
  //...
  this.Acme.Bar = this.Acme.Bar || {};
  this.Acme.Bar.Foo = Foo;
  //...
}).call(this);

(function () {
  var Foo = this.Acme.Bar.Foo;
  //...
}).call(this);

// From another library
let foo = new Acme.Bar.Foo();
let bar = foo.bar();

if (foo instanceof Acme.Bar.Bar) {
   console.log('Bar!');
}
```

**Comment by mairatma** [comment]
I like the tree structure approach better, the final code is cleaner to read instead of having path strings. Let's go with this one then, unless you need the strings version as well.

**Comment by mairatma** [comment]
I've created the issues, so I'll close this one since we can talk about each change on its own issue now.

**Comment by marcospassos** [comment]
Yeah, dot notation is sexier :)
