### ISSUE TITLE
Error when exporting function definitions directly

### ISSUE THREAD

**Issue by nfrasser** [mairatma/babel-globals#6]
I'm trying to compile a file that looks like this:

``` js
export default function foo() {
  console.log("Hello World!");
}
```

This is a [valid module declaration](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact%2Cstage-2&code=export%20default%20function%20foo%28%29%20%7B%0A%20%20console.log%28%22Hello%20World!%22%29%3B%0A%7D) in ES6. But with babel-globals, I get this error

```
TypeError: ./foo.js: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got "FunctionDeclaration"
```

To fix it, I have to rewrite the module like this

``` js
function foo() {
  console.log("Hello World!");
}
export default foo;
```

I'd like to always be able to use the first way. I'm guessing this error happens due to the module rewrite, which results in invalid code like this:

``` js
this.myGlobals.foo = function foo() { /*...*/ }
```

I'd like to submit a fix, but I'm having trouble figuring out where in the code the rewrites happen. Any suggestions on where to start?

P.S.: Thanks a ton for this library!

**Comment by mairatma** [comment]
This makes total sense, I've been trying to use this syntax in projects of mine and getting this error, but I was assuming it was wrong syntax or a babel bug, hadn't realized it might be caused by this project! Thanks for pointing that out!

Unfortunately I'm so busy these days, I don't think I'll be able to look into this very soon. But, if you want to investigate, it's probably happening in a dependency of this project, which is the one doing the rewrites. It's another project of mine, [babel-plugin-globals](https://github.com/mairatma/babel-plugin-globals), and probably something that should be done in this method: https://github.com/mairatma/babel-plugin-globals/blob/master/index.js#L185. I think in this case we need to first define the function by itself, and export its identifier.

If you manage to work on this, just send me a pr there and I'll review quickly :)

**Comment by nfrasser** [comment]
@mairatma done! mairatma/babel-plugin-globals#5
